import type { IncomingHttpHeaders } from 'node:http';
import type { Stats } from 'node:fs';
import { stringPredicate } from '../../util/regexpFlags.mts';
import type { ReadOnlyFileHandle } from '../../util/ReadOnlyFileHandle.mts';
import type { Negotiator, NegotiationOutputHeaders } from '../request/Negotiator.mts';

export interface FileFinderOptions {
  /**
   * Also serve files from sub-directories.
   * Can be set to a number to control the depth of subdirectories served (where 0 means no
   * subdirectories).
   *
   * @default true
   */
  subDirectories?: boolean | number | undefined;

  /**
   * Configure case sensitivity of paths.
   *
   * `exact`: ensure that the path exactly matches the filesystem, even if the filesystem
   * itself is case insensitive.
   *
   * `filesystem`: use the case sensitivity of the filesystem.
   *
   * `force-lowercase`: lowercase all requests before forwarding to the filesystem (this
   * can achieve case insensitivity on otherwise case sensitive filesystems, but only if
   * all files and folders are stored as lowercase).
   *
   * @default 'exact'
   */
  caseSensitive?: 'exact' | 'filesystem' | 'force-lowercase' | undefined;

  /**
   * Allow serving dotfiles.
   * If `true`, all dotfiles will be available (note this can be a security risk if you have
   * sensitive hidden files or directories in the directory being served, such as `.git`).
   * If you only need some dotfiles to be made available, you can use `permit` instead, which
   * lets you allow specific file / directory names.
   *
   * @default false
   */
  allowAllDotfiles?: boolean | undefined;

  /**
   * Allow serving files which begin or end with a tilde.
   * These are commonly backup files (e.g. generated by vim when editing a file), and may or
   * may not be a security risk to expose, depending on your setup.
   * If `true`, all tilde files will be available.
   * If you only need some tilde files to be made available, you can use `permit` instead, which
   * lets you allow specific file / directory names.
   *
   * @default false
   */
  allowAllTildefiles?: boolean | undefined;

  /**
   * Serve index files when requested directly (e.g. `/foo/index.htm`).
   * By default, index files (listed in `indexFiles`) are only served if the directory is requested.
   *
   * @default false
   */
  allowDirectIndexAccess?: boolean | undefined;

  /**
   * Hide arbitrary files from direct access. For example, when supporting content negotiation
   * you may wish to block direct access to the "negotiated" variants of files such as `/\.gz$/`.
   *
   * Matches are performed on each path component. If any match, the file is hidden. Regular
   * expressions are automatically made case insensitive if `caseSensitive` is `'filesystem'` or
   * `'force-lowercase'`
   *
   * In cases where both match the same path component, `allow` overrides `hide`.
   *
   * @default []
   */
  hide?: ReadonlyArray<string | RegExp> | undefined;

  /**
   * Allow access to specific files which would otherwise be blocked as a dotfile, tilde file, or
   * hidden by `hide`.
   *
   * @default ['.well-known']
   */
  allow?: ReadonlyArray<string> | undefined;

  /**
   * Files to look for if a directory is requested.
   * Note that direct access to these files will be blocked unless `allowDirectIndexAccess` is `true`.
   *
   * If an empty list is provided, no index files will be served.
   *
   * @default ['index.htm', 'index.html']
   */
  indexFiles?: ReadonlyArray<string> | undefined;

  /**
   * Suffixes to try appending if the requested file does not exist.
   *
   * For example, specifying `['.html']` will serve `foo.html` at `/foo`
   *
   * @default []
   */
  implicitSuffixes?: ReadonlyArray<string> | undefined;

  /**
   * Content negotiation to apply to files.
   *
   * This can be used to respond to the `Accept`, `Accept-Language`, and `Accept-Encoding` headers.
   *
   * Note that file access is checked *before* content negotiation, so you must still provide a
   * base "un-negotiated" file for each file you wish to serve (which will also be used in cases
   * where users do not send any `Accept-*` headers, and where no match is found)
   *
   * @default undefined
   */
  negotiator?: Negotiator | undefined;
}

export interface FileFinder {
  find(
    pathParts: ReadonlyArray<string>,
    reqHeaders?: IncomingHttpHeaders | undefined,
    warnings?: string[] | undefined,
  ): Promise<ResolvedFileInfo | null>;

  toNormalisedPath(pathParts: ReadonlyArray<string>): ReadonlyArray<string>;

  isStaticListing: boolean;
  staticPaths?: () => Set<string>;
}

export class FileFinderRules {
  /** @internal */ declare readonly _subDirectories: number;
  /** @internal */ declare readonly _caseSensitive: 'exact' | 'filesystem' | 'force-lowercase';
  /** @internal */ declare private readonly _allowAllDotfiles: boolean;
  /** @internal */ declare private readonly _allowAllTildefiles: boolean;
  /** @internal */ declare readonly _allowDirectIndexAccess: boolean;
  /** @internal */ declare readonly _allow: Set<string>;
  /** @internal */ declare private readonly _hide: (v: string) => boolean;
  /** @internal */ declare readonly _indexFiles: ReadonlyArray<string>;
  /** @internal */ declare readonly _indexFilesSet: Set<string>;
  /** @internal */ declare readonly _implicitSuffixes: ReadonlyArray<string>;
  /** @internal */ declare readonly _negotiator: Negotiator | undefined;

  /** @internal */ constructor({
    subDirectories = true,
    caseSensitive = 'exact',
    allowAllDotfiles = false,
    allowAllTildefiles = false,
    allowDirectIndexAccess = false,
    allow = ['.well-known'],
    hide = [],
    indexFiles = ['index.htm', 'index.html'],
    implicitSuffixes = [],
    negotiator,
  }: FileFinderOptions) {
    this._subDirectories = subDirectories === true ? Number.POSITIVE_INFINITY : subDirectories || 0;
    this._caseSensitive = caseSensitive;
    this._allowAllDotfiles = allowAllDotfiles;
    this._allowAllTildefiles = allowAllTildefiles;
    this._allowDirectIndexAccess = allowDirectIndexAccess;
    this._indexFiles = indexFiles;
    this._implicitSuffixes = ['', ...implicitSuffixes];

    this._allow = new Set(allow.map((v) => this._normalise(v)));
    this._hide = stringPredicate(hide, !caseSensitive);
    this._indexFilesSet = new Set(indexFiles.map((f) => this._normalise(f)));

    this._negotiator = negotiator;
  }

  /** @internal */ _normalise(part: string) {
    return this._caseSensitive === 'exact' ? part : part.toLowerCase();
  }

  /** @internal */ _checkPermitted(part: string) {
    const normed = this._normalise(part);
    if (this._allow.has(normed)) {
      return true;
    }
    const trimmed = normed.trim(); // Windows may trim spaces from filenames
    if ((trimmed[0] === '~' || trimmed[trimmed.length - 1] === '~') && !this._allowAllTildefiles) {
      return false;
    } else if (trimmed[0] === '.' && !this._allowAllDotfiles) {
      return false;
    } else if (this._hide(trimmed)) {
      return false;
    } else {
      return true;
    }
  }

  /** @internal */ _toNormalisedPath(pathParts: ReadonlyArray<string>) {
    const last = pathParts[pathParts.length - 1];
    if (last && this._indexFilesSet.has(this._normalise(last))) {
      return pathParts.slice(0, pathParts.length - 1);
    }
    return pathParts;
  }
}

export interface ResolvedFileInfo {
  /** An active filehandle for the resolved file. Note that this MUST be closed by the caller. */
  handle: ReadOnlyFileHandle;
  /** The file name of the requested file (after adding implicit extensions and index files, but without content negotiation variations such as `.gz`) */
  canonicalFilename: string;
  /** The full path of the file being served from the filesystem (includes negotiated variations such as `.gz`). Note for files inside zips, this will be of the form `/path/to/file.zip/path/within/zip` */
  filesystemPath: string;
  /** Filesystem stats about the resolved file */
  stats: Stats;
  /** Response headers relevant to the negotiation of this file */
  headers: NegotiationOutputHeaders;
}
