import type { IncomingMessage } from 'node:http';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createWriteStream } from 'node:fs';
import type { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import type { ReadableStream } from 'node:stream/web';
import { addTeardown, getAbortSignal } from '../../core/close.mts';
import { STOP } from '../../core/RoutingInstruction.mts';
import { makeMemo } from '../Property.mts';

interface SavedFile {
  path: string;
  size: number;
}

export interface TempFileStorage {
  /** The full path to the temporary directory created for file storage. */
  dir: string;
  /**
   * Allocate a new systematic filename.
   * The returned name is guaranteed to be unique across calls to `nextFile`,
   * but is not guaranteed to be distinct from other files in the temporary directory
   * (i.e. if files have been created with names not generated by `nextFile`).
   *
   * @returns the full path to a unique filename in `dir`.
   */
  nextFile: () => string;
  /**
   * Save a stream to a file in the temporary directory.
   * Uses `nextFile` internally to generate a unique name for the file.
   * @returns the path and size of the saved file
   */
  save: (
    stream: Readable | ReadableStream,
    options?: { mode?: number | undefined } | undefined,
  ) => Promise<SavedFile>;
}

export const makeTempFileStorage = /*@__PURE__*/ makeMemo(
  async (req: IncomingMessage): Promise<TempFileStorage> => {
    const signal = getAbortSignal(req);
    if (signal.aborted) {
      throw STOP;
    }
    signal.throwIfAborted();
    const dir = await mkdtemp(join(tmpdir(), 'upload'));
    addTeardown(req, () => rm(dir, { recursive: true }));

    let fileIndex = 0;
    const nextFile = () => {
      if (signal.aborted) {
        throw STOP;
      }
      return join(dir, (++fileIndex).toString(10).padStart(6, '0'));
    };

    return {
      dir,
      nextFile,
      save: async (stream, { mode = 0o600 } = {}) => {
        const tempUploadPath = nextFile();
        const fileStream = createWriteStream(tempUploadPath, { mode });
        try {
          await pipeline(stream, fileStream, { signal });
          return { path: tempUploadPath, size: fileStream.bytesWritten };
        } finally {
          fileStream.close();
        }
      },
    };
  },
);
